### ISSUE TITLE
Documentation Improvements [JOSS Review]

### ISSUE THREAD

**Issue by JesperDramsch** [rgmyr/corebreakout#11]
I would not be able to recreate the examples from the available documentation. 

It appears that while docstrings are available, no documentation was generated and snippets of documentation are spread throughout the structure of the project. I.e. there is a [docs folder](https://github.com/rgmyr/corebreakout/tree/master/docs), however, utility scripts have a separate short description in the [utility script folder](https://github.com/rgmyr/corebreakout/tree/master/scripts/post_labeling_tools), which however does not describe all utility scripts. Moreover, there are [example notebooks](https://github.com/rgmyr/corebreakout/tree/master/notebooks) in the root of the project and in the [test/ directory](https://github.com/rgmyr/corebreakout/tree/master/tests/notebooks), which is not directly clear, why these are kept separate, or how they are located separately from the other notebooks. 

## Functional API
I was not able to locate the functional API documentation. I see docstrings are available, but I do not see any documentation of the functions and classes.

From reading the readme.md and the paper I am guessing that there is a `CoreColumn`, which I don't see any description of other than "it is essential to the project". And it seems there is a `CoreSegmenter` which apparently has a `.segment` and a `segment_all` method. Seeing that you have a docstring, what was the choice to not auto-generate API documentation that people can use?

I don't think it's good for the project adoption if users have to sift through the code to find the documentation (I remember in one document, you do link directly to the code "for more information" but I can't find it right now). I don't think this is good practice, and creating central documentation to get information about usage, without having to deeply understand the design choices you the authors make about placing classes, functions and methods, would be extremely beneficial and quite frankly necessary.

**Comment by JesperDramsch** [comment]
[Link to Issue](https://github.com/openjournals/joss-reviews/issues/1969)

**Comment by rgmyr** [comment]
Hi Jesper,

Thanks for your feedback. I'm certainly open to reorganizing the docs to be more useful/helpful. To answer a few questions:
- I didn't auto-generate API docs just because I've had issues getting that stuff (e.g., `sphinx`) to work well in the past. I'll look into it again and give it a shot though. I'll also try to clean up the scripts folder + their docs.
- The notebooks at `tests/notebooks` are separate because they're meant to be run as 'tests' (i.e., after making changes to make sure that column plots / segmentation outputs are still as expected). And `make_endpts_data.ipynb` was just used to generate 'correct' answers for some `pytest` tests and make some doc images.

**Comment by JesperDramsch** [comment]
Yeah, I've heard that about sphinx before. However, as it stands I don't think the documentation is sufficient for me to figure out how to use the library.

**Comment by rgmyr** [comment]
Hi @JesperDramsch, I've finally gotten around to this and have compiled some html documentation pages. I am still cleaning up some of the `.rst` structure, and plan to host them on a `readthedocs` page in the near future, but for now you can view them with a simple HTTP server (e.g., `python -m SimpleHTTPServer`) in the `docs/_build` folder if you are interested.

**Comment by rgmyr** [comment]
@JesperDramsch Some updates forthcoming, but just FYI, current docs are now hosted at: https://corebreakout.readthedocs.io/en/latest/
