### ISSUE TITLE
JOSS reivew notes openjournals/joss-reviews#1969

### ISSUE THREAD

**Issue by jessepisel** [rgmyr/corebreakout#9]
Howdy corebreakout team,

Here are some of my notes from my review of the package. 

- After updating the install I was able to get the package installed and running on both CPU and GPU.
- The directions were clear on how to label new datasets. I would like to know how many examples of each class I should have for training on a new dataset. 
- The documentation on core orientation in `layout_parameters.md` answered all my questions about using different image layouts. 
- Overall the documentation looks to be in good shape. I think that it would be beneficial to bundle `Jupyter` in with the `corebreakout-env` install so that users don't have to install it separately to run through the example noteooks. 

Here are some of my notes on the code:
- `datasets/utils.py` needs a bit of clean up for the initial release. Remove the commented out function and make sure you have all your docstrings for user functions.
- The rest of the classes and functions look to be in good shape. I think you should run the entire package through a linter like `Pylint` or `Flake8` just to clean up things a bit. Everything in the package works and I was able to segment out the core images in `assets.zip`.

Overall I like how it is laid out, the documentation made it easy for me to get up and running with the core image segmentation. I think just some housekeeping on the repo and it should be good to go!

Let me know if you have any questions or need any other clarification! Nice job team!

-Jesse

**Comment by rgmyr** [comment]
Hi Jesse,

I've updated the repo with some of your suggestions in 1a851e0:

- Added a note to `creating_datasets.md` about number of training images/instances
- Added `jupyter` to `requirements.txt`
- Went ahead and deleted `datasets/utils.py`. Those functions were for a long outdated iteration of this project where I was manually painting images in a photo editor to label them.

I will look into using a linter and update that in a future commit.

Thanks for your feedback!
